### ISSUE TITLE
Username page: Design

### ISSUE THREAD

**Issue by ChickenDeLuxe** [zabooz/4B-s-Baby#230]
Picture
IDENTITY WIZARD H3
Erstelle einen einzigartigen Benutzernamen. Du kannst bis zu drei neue Namen in der Liste belassen. Pro-Tipp: Speichere die Namen, die dir besonders gut gefallen, mit Clippy! usw. usw. 
3 input fields - left-right 
insert divider (a very, very light divider. think of white space. do not even think about anything else.)

CTA1: creates username (including paramters??)
No german beta in V1
max 3 entries? --> inform the user beforehand
no scrollbar (resize left/right, bottom)
CTA 2: delete/refresh all

rename fantasiekreaturen in fantasiewesen, generally: match title/name with array name

V2: 
Mind Maestro: 
Carousel - V2
Instead

V2: Create Container: fixed size

**Comment by ChickenDeLuxe** [comment]
2 suggestions: 

![Uploading Password Playground_IdentityWizard_1.png…]()

**Comment by ChickenDeLuxe** [comment]
![Password Playground_IdentityWizard_small](https://github.com/user-attachments/assets/1b789984-4c6d-496f-8393-8e51a8e1f7c2)

![Password Playground_IdentityWizard_1](https://github.com/user-attachments/assets/0a8999b6-7cec-474e-be8e-aa8e2cca21c0)

**Comment by ChickenDeLuxe** [comment]
Ad 1: follows the design (small card), but: only 2 usernames
Ad 2: like it better... and everything's very neat. 

Forgot to add the clipboard.

**Comment by ChickenDeLuxe** [comment]
Clipboard, alignment (in card) fixed: 

![Password Playground_IdentityWizard_1](https://github.com/user-attachments/assets/4e7ed2e1-65d5-4c16-8468-d2d8e56430bb)

**Comment by Zappls** [comment]
did the thing
