### ISSUE TITLE
Wildcard issue 

### ISSUE THREAD

**Issue by ChickenDeLuxe** [zabooz/4B-s-Baby#234]
mojo karte: bei den links is ein space mitunterstrichen -- **done, redesign**

inputs und dropdowns sind nicht einheitlich auf der ganzen seite 

das wort passwortlänge wird in den dropdown bei glyphsorcery eingefügt um den dropdown zu verbreitern. Dann wird der button unter den dropdown geschoben damit es einheitlicher aussieht. **done, redesign**

username card background ist nicht die gleiche farbe wie bei den anderen cards **schriftfarbe überall (?) auf #212529 geändert**

foto hochladen hat anderen borderradius als buttons **done, redesign**

bei glyph sorcery ist ein tippfehler bei Passwort *glyph sorcery überall noch falsch geschrieben, wird geändert*

mind maestro überschrift ist linkbündig und fragenkarten verändern größe von slide zu slide *wird redesigned*

make password text ist fetter als anderswo? **done, redesign**
bei runetranslator steht password im input statt passwort
excalibur button sollte gleich breit wie input sein **done, redesign**

**Comment by zabooz** [comment]
third card on landing page acting wierd. The image wont resize correctly.
